name: VRT Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/golden_test/**'

jobs:
  check-visual-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Download Baseline
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: vrt-baseline.yml
          branch: main
          name: vrt-baseline
          path: test/golden_test/goldens/ci/

      - name: Run Golden Tests
        run: flutter test --tags=golden
        env:
          CI: true

      - name: Upload Diff Images
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vrt-diff
          path: test/golden_test/failures/
          retention-days: 7
